// This file was automatically generated by ADQ214_devkit.tcl
// Either modify this file as you wish, or rebuild the project using the script, in order to change part number.
`define USER_LOGIC_PARTNUM_1 16'd0
`define USER_LOGIC_PARTNUM_2 16'd0
`define USER_LOGIC_PARTNUM_3 16'd0
`define USER_LOGIC_PARTNUM_REV 16'd0
